### ISSUE TITLE
'X-Frame-Options' to 'sameorigin'

### ISSUE THREAD

**Issue by slobberbone** [joshdick/miniProxy#104]
Hello, good works done in this project ! I use it to allow for a personnal usage in a portal to display several site I'm using every time !
For some of website I'm trying to access, I've got this error : Refused to display 'https://securewebsite.fr/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Is there any way to by pass this ?
Thank you

**Comment by zpit367** [comment]
take a look at this (not my code)
http://jsfiddle.net/dkdnaxaq/
