### ISSUE TITLE
Fault when visiting https://www.somedomain.com

### ISSUE THREAD

**Issue by chaihahaha** [joshdick/miniProxy#106]
When visiting http sites: like "http://www.bing.com", everything goes right.
But when visiting https sites: like "https://www.google.com", only a blank page(without any pictures or words) is shown.
My server is run on windows server and php5.4 and cannot run with https.

**Comment by joshdick** [comment]
Your server OS is Windows, but which web server are you using? Apache? IIS? Something else? Can you access HTTPS sites using a web browser directly on the server machine?

**Comment by chaihahaha** [comment]
Thanks very much for your reply! I'm using IIS web server, and I can access HTTPS on my server machine. I tried but can't find out why.

**Comment by joshdick** [comment]
Try this: https://scribesroom.wordpress.com/2016/07/11/configuring-phpcurl-on-windowsiis-https-site/
