### ISSUE TITLE
miniproxy dosn't work

### ISSUE THREAD

**Issue by mahmoudxp** [joshdick/miniProxy#107]
Hi
minproxy was working properly at 2 month ago  but now miniproxy dosn't work. any idea?

**Comment by joshdick** [comment]
Can you be more specific?

**Comment by mahmoudxp** [comment]
I have a website in Iran and as you may know,in my country some social media such as youtube is blocked. I planned to use php proxy to stream youtube videos on my website, my host is located in germany. The miniproxy would work well at first but from last week it suddenly stopped working, i mean when i use the script for browsing blocked website, i received the gov message related to blocked websites as if no proxy

**Comment by joshdick** [comment]
miniProxy has historically not worked well with streaming video sites, so if you were trying to use it with YouTube I'm not too surprised it's not working correctly.

Without specific information about which sites aren't working there's not much I can do to help.

**Comment by BenNottelling** [comment]
Actually, they are saying that it is no longer bypassing the block in their country.. (right?)
@mahmoudxp are you sure you were trying to view the website through the proxy? Also, is it hosted in the country with the same block?
