### ISSUE TITLE
HTTP 502 Bad Gateway 

### ISSUE THREAD

**Issue by Bonveio** [joshdick/miniProxy#109]
I use this miniProxy in PHP 7.0 and this is working , but i try to change to old version (PHP 5.2) to test other php file to my webserver and this error occured , i try to back to 7.0 and this error is permanent and cant be fixed, please help.

**Comment by joshdick** [comment]
miniProxy supports PHP version 5.4.7 and newer.

This seems like a problem with your web server rather than with miniProxy, so I'm going to close this issue, but please feel free to continue the conversation either way.

**Comment by Bonveio** [comment]
Thanks for response @joshdick
i try the latest php version 7.2 and it works perfectly
