### ISSUE TITLE
Proxy doesn't work with websockets

### ISSUE THREAD

**Issue by BenNottelling** [joshdick/miniProxy#114]
I noticed this with my proxy on my website that's got some fixes in it that let me login to and load Netflix, but when i pick a movie to watch it just shows a black screen. Checking the console shoes that websockets are showing an error 400

It would be super cool to see if we can get them to work!

**Comment by bionichuman** [comment]
@BenNottelling I need this too. Same problem. Just black screen...

**Comment by BenNottelling** [comment]
I forgot to mention this, but perhaps a temporary solution may be to provide an option that will simply not proxify the websocket connections

**Comment by bionichuman** [comment]
@BenNottelling That is a good idea. But how do we do that?
