### ISSUE TITLE
Large amount video not support

### ISSUE THREAD

**Issue by Venupk-88** [joshdick/miniProxy#124]

**Comment by Venupk-88** [comment]
500 Mb video not convert to proxy url

**Comment by FranciscoPaixao** [comment]
What a pity. I wanted to use it on my video server.

**Comment by BenNottelling** [comment]
This is almost definitely an issue with your server and not with miniProxy. It could be worked around here on our end, but I'd say it's likely out of scope for the project as a simple web proxy
