### ISSUE TITLE
How do I open miniProxy?

### ISSUE THREAD

**Issue by qfaq** [joshdick/miniProxy#130]
Everytime I try opening mini-proxy through firefox it just redownloads it or displays it as a txt file. Compared to other php files that actually load. Is there any html? The installation just said to "upload it to your webserver" but does not give much more than that.

Edit: Same issue on google chrome.
<img width="1280" alt="Screen Shot 2019-06-20 at 9 08 55 PM" src="https://user-images.githubusercontent.com/49662620/59897014-a3480500-939f-11e9-99c4-93465b7aa118.png">

**Comment by BenNottelling** [comment]
In that picture you've upload you're loading the php file locally, which won't work as it needs to get server through a webserver with php installed to load correct. All html is contained in the php file, it's the only thing you need to upload

**Comment by qfaq** [comment]
How would I do this? Any programs in mind?

**Comment by BenNottelling** [comment]
Do you have a website or a webserver with PHP installed?

**Comment by qfaq** [comment]
Well right now i’m using Netlify connected to my github to host my website.

**Comment by BenNottelling** [comment]
Looks like an  issue with using Netlify

**Comment by qfaq** [comment]
Hello, I just tried using another hoster, and if i just an embed i think i
will be ok. Thank you very much for the help.

**Comment by joshdick** [comment]
The problem was that your original web server did not have PHP enabled. miniProxy is written in PHP and therefore needs a sever with PHP available in order to function.

Glad you were able to get past the issue!
