### ISSUE TITLE
Set custom referer

### ISSUE THREAD

**Issue by gmkbenjamin** [joshdick/miniProxy#133]
Is it possible to set custom referer? 
curl_setopt function (CURLOPT_REFERER and CURLOPT_USERAGENT) doesn't seem to work for me.

**Comment by BenNottelling** [comment]
User agent is set here
https://github.com/joshdick/miniProxy/blob/master/miniProxy.php#L104

**Comment by gmkbenjamin** [comment]
Thanks Ben. Had to comment out CURLOPT_HTTPHEADER for useragent and referer to work.
