### ISSUE TITLE
Question about chunked transfer encoding

### ISSUE THREAD

**Issue by ovizii** [joshdick/miniProxy#135]
The proxy works perfect except for a site which I need regular access to. miniProxy is giving me an error which I can't figure out. 

Can someone explain if this is fixable with miniProxy or if this simply won't work?

`Connection error 501: chunked transfer encoding not supported`

**Comment by joshdick** [comment]
I don't have much to go on without more information about the site you're trying to access and the server you're running miniProxy on.

**Comment by ovizii** [comment]
oh, well, the server I am running miniproxy on is my own root server so if there's anything to change I can do that but I wouldn't want to share its URl here publicly as its only for my own usage. can I somehow send you the link directly without publicly sharing it? 

Regarding the site I am trying to reach, its a self-hosted Proxmox instance. I can access it just fine but some "actions" like restart server, etc. gives the above error.

**Comment by joshdick** [comment]
This seems like an issue with the server you're running miniProxy on.
