### ISSUE TITLE
I want browsing from uk

### ISSUE THREAD

**Issue by manishkumarpatel** [joshdick/miniProxy#137]
when i enter url google.com then at bottom it shows french, i want to browsing from other countries like uk, usa. I need to country configuration in code.

**Comment by joshdick** [comment]
Thanks for using miniProxy!

When using miniProxy, the apparent country depends entirely on the physical location of the server where miniProxy is installed.

Because of this, it is not possible to add country configuration as you suggest, and so I'm closing this issue.
