### ISSUE TITLE
Redirect URLs which are not on whitelist

### ISSUE THREAD

**Issue by Perflyst** [joshdick/miniProxy#138]
I would like to request an option to redirect non whitelisted domains to their normal urls instead of showing the error page.

**Comment by joshdick** [comment]
Interesting idea, but I am not going to implement an option like this for two reasons:

* Configuration options that depend on other options are inherently confusing
* If accidentally [mis]configured, it might be easy for someone to think they're still browsing a configured site through the proxy when in fact they've been redirected out of the proxy. I think it could be confusing, or even dangerous, for the proxy to be able to be configured to silently stop proxying certain sites.

Thanks for the suggestion in any case, though!

**Comment by Perflyst** [comment]
For anyone who may needs this, just add `header('Location: '.$url);` in `if (!$urlIsValid) {..}`
