### ISSUE TITLE
Use with another server

### ISSUE THREAD

**Issue by redskate** [joshdick/miniProxy#19]
Hello! Thank you for publishing this nice php program!

Before I completely reverse engineer it, I would like to ask you some configuration details.

I have a site http://myserver.com with php 5 and I would like to take the content from another server - say http://12.34.56.78:12345 which ist on an IP wich is not on a NIS. So I need a bridge for that using http://myserver.com which is in NIS...

How should I configure your nice program in order to call elements from http://12.34.56.78:12345 ??

Thanks a lot in advance!
Chears

**Comment by etiktin** [comment]
If the server where miniProxy is installed can reach http://12.34.56.78:12345 , then you can use miniProxy as usual (e.g. http://yourMiniProxyRunningServer.com/miniProxy.php/http://12.34.56.78:12345/somePage.html).

**Comment by redskate** [comment]
Thank you - yes. I could make it run so. 
I discovered a problem in the preg_match - pattern must have surrounding "/" - 
furthermore (I try to proxy a whole website) it is running up to 80%. There are still strange bevaviour concerning css and javascript ... (other issues).

**Comment by etiktin** [comment]
Glad to help.
If you find a specific bug, it's better if you open a separate issue for it so we can track it. Also feel free to open PRs with fixes.
