### ISSUE TITLE
CSS / Javascript seems to get partially broken

### ISSUE THREAD

**Issue by redskate** [joshdick/miniProxy#20]
Hi!

I finally set under semlab.ch an .htaccess containing RewriteRule ^(.+)/(.+)$ miniProxy.php?u=$2
and I modified the url gathering method by setting  -  $url=$_REQUEST['u'];  -  instead of your method.

I would like to take the content from http://82.192.234.100:25963/,  so concretely when I issue a call to

http://semlab.ch/en-home-page-semweb I would like to show the content of
http://82.192.234.100:25963/en-home-page-semweb

This is under none of Chrome/Opera/Safari/Firefox the case: It seems that some javascript be broken during transfer. The website is somehow ruined by this. 

Do you have any idea?

Cheers

**Comment by lesander** [comment]
Or you could just set the DNS of that domain to point to that IP address.

**Comment by redskate** [comment]
No (thanks), because what I fear is that some paranoid institution block the ip  http://82.192.234.100:25963  so a simple pointing  
1) is not possible because my IP is not served as an IP to be registered.
2) does not solve the IP block

So I have to solve it with a proxy.

**Comment by redskate** [comment]
What I discovered is that the program "proxifies" the content of each served file, putting a miniProxy.php/url to make complete urls. This ist not compliant with a use with .htaccess since the proxified urls should be again de-proxified by .htaccess.  But even letting .htaccess by side, calling e.g. http://semlab.ch/p.php/de-home-page-semweb/ does not come with a complete website, probably the proxyfing ist not enaugh for this site.

Cheers

**Comment by redskate** [comment]
For instance instead of 

http://semlab.ch/p.php/http://82.192.234.100:25963/_/wordpress/wp-content/themes/inceptio/images/search.png

the proxifier function makes

http://semlab.ch/p.php/http://82.192.234.100/_/wordpress/wp-content/themes/inceptio:25963/images/search.png

which of course occults the png file

Cheers

**Comment by redskate** [comment]
Well I found a proxy which run at once.  https://code.google.com/p/php-proxy/
I think I am glad

Thank you anyway

Cheers
