### ISSUE TITLE
Cannot proxy post data of uploaded file.

### ISSUE THREAD

**Issue by XGowe** [joshdick/miniProxy#23]
Hello,
I notice that the program can't proxy post data of uploaded file.The script use file_get_contents("php://input") to get raw post data, but it seems to be not available in some situations.
After searching the Internet, I find it that something associated with this problem have been metioned at http://www.php.net/manual/en/ini.core.php#ini.enable-post-data-reading and https://secure.php.net/manual/en/wrappers.php.php#wrappers.php.input. The solution mentioned can only available after PHP 5.4 and need to change the php.ini .
Are there some workarounds to make it work?
Thanks a lot in advance.
Gowe

**Comment by XGowe** [comment]
Solved:
https://gist.github.com/XGowe/ef89985418bc176580d5

**Comment by un-fmunozs** [comment]
I noticed this issue was closed but there's still no support for uploading files on the official miniproxy, I'll try XGowe changes.
