### ISSUE TITLE
Relative URLs after Redirects

### ISSUE THREAD

**Issue by CarlAmbroselli** [joshdick/miniProxy#25]
If a page redirects (and Curl follows the redirect) then the relative urls are still rewritten to the page before the redirect.

Example:

1. Open https://google.com
2. it redirects to https://www.google.com (This is handled by Curl.)
3. Relative urls are rewritten to https://google.com/asd instead of https://www.google.com/asd

**Comment by CarlAmbroselli** [comment]
It can be fixed by adding:
```
  preg_match_all('/^Location:(.*)$/mi', $responseHeaders, $matches);
  if(!empty($matches[1])) {
    define("WEBPAGE_URL", trim($matches[1][0]));
  } else {
    define("WEBPAGE_URL", '');
  }
```

at the end of the curl command and then add the following in rel2abs:

```
  if(strlen(WEBPAGE_URL) > 0) {
    $base = WEBPAGE_URL;
  }
```

But I'm sure there is a better way to implement it then this quick fix.

**Comment by joshdick** [comment]
I wonder if this could this be fixed by disabling `CURLOPT_FOLLOWLOCATION`, intercepting the `location` header in the response headers, and feeding the value back into the proxy?

**Comment by rothkj1022** [comment]
This would be fixed with this pull request:
https://github.com/joshdick/miniProxy/pull/33

**Comment by joshdick** [comment]
After thinking about this for a while, I came up with two different ways to solve it.

The first way is implemented using my idea above of manually parsing Location headers, and can be found at 230e0d25ab02706ff04d19db3ee781d9cd6b175c.

The second way is simpler and involves comparing the response URL reported by cURL to the users' request URL, and can be found at 1db9b219ff35dd98e8d3a0a610f2c6adab0a5ad7.

Would appreciate thoughts/code reviews from @etiktin and @rothkj1022 as to which is better!

**Comment by joshdick** [comment]
I decided to fix this using the simpler solution I originally proposed in 1db9b21.
