### ISSUE TITLE
什么时候才能支持cookie呢？期待！！

### ISSUE THREAD

**Issue by 1042799521** [joshdick/miniProxy#28]
真心想使用此访问facebook

**Comment by joshdick** [comment]
Lack of cookie support is a known limitation of miniProxy, and a nontrivial problem to solve (see #24).

I'm not going to implement it anytime soon, but may still get around to it eventually! :)

**Comment by 1042799521** [comment]
加油！

Josh Dick
notifications@github.com>于2016年1月1日 周五00:26写道：

**Comment by 1042799521** [comment]
但是glopy已经支持cookie了

liu lu <qq1042799521@gmail.com>于2016年1月1日 周五00:29写道：
