### ISSUE TITLE
Add noindex tags to proxied page

### ISSUE THREAD

**Issue by RahulBasu2001** [joshdick/miniProxy#30]
http://webmasters.stackexchange.com/questions/88492/stop-google-from-crawling-proxied-pages-but-still-allow-the-proxy-itself-to-be-f

^^I had to remove the proxy because google started using up all my bandwidth.
We need to make the proxy add the following line in the head section of the proxied page:

`<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">`

**Comment by RahulBasu2001** [comment]
OK, I think I got it...
The end of your proxy.php document has the following line:
'echo "\n" . $doc->saveHTML();'
Modify it to this:
`echo "\n <meta name="robots" content="nofollow,noindex">\n" . $doc->saveHTML();

Not the neatest solution as it doesn't add it to the `<head>` section, but it works...

**Comment by joshdick** [comment]
Thanks for the report -- good suggestion!

In 50d0817, I added an [X-Robots-Tag header](https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag) for all proxified pages, which should resolve this issue.
