### ISSUE TITLE
Possible to set a start page?

### ISSUE THREAD

**Issue by Jamman** [joshdick/miniProxy#34]
Ok, this maybe isn't an issue - but I'm wanting to use this to whitelist a single page

**Comment by joshdick** [comment]
You can do this in two steps:

1) Add your domain to `$whitelistPatterns` at the top of miniProxy.php, and
2) Replace [this line](https://github.com/joshdick/miniProxy/blob/9a7a0d0747646d3b7b16097953af875b153bea43/miniProxy.php#L185) with something like `$url = "http://your-site.com";`

**Comment by Jamman** [comment]
Step two works fine, but step one is giving me troubl - I've never found
the correct usage of the whitelisting

This fails me

$whitelistPatterns = array(facebook.com/nzlollies
>   //Usage example: To support any URL at example.net, including
> sub-domains, uncomment the
>   //line below (which is equivalent to [
> @^https?://([a-z0-9-]+\.)*example\.net@i ]):
>   //getHostnamePattern("")
> );


The other option for me would be to make the page totally static - then I
would add facebook.com and not worry about blocking other content.

Any ideas?

Regards

Andrew

**Comment by joshdick** [comment]
I've touched on your question in our conversation in #35. If you have more questions around this, please continue to use #35 even though it's closed, instead of opening more issues.
