### ISSUE TITLE
multiple whitelisted sites and regular expression

### ISSUE THREAD

**Issue by Jamman** [joshdick/miniProxy#35]
I've discovered I can use 
`getHostnamePattern("facebook.com\/lollies")`
to limit to a very specific page - however of course this fails to get a lot of required CSS etc...

Is there a way to whitelist multiple URLs/domains?

**Comment by Jamman** [comment]
Oh the regular expression bit - I can't get the regular expression to work at all... if I paste 
`$whitelistPatterns = array([ @^https?://([a-z0-9-]+\.)*example\.net@i ]`
I get an error "Parse error: syntax error, unexpected '^' in ..."

**Comment by Jamman** [comment]
While I'm making a pest of myself... is it possible to use this inside a folder in a subdomain? - it seems to fail if you locate the proxy file in a subdomain

**Comment by joshdick** [comment]
I don't exactly understand your subdomain question; where the proxy is hosted should not affect its whitelisting capability.

You can whitelist multiple URLs/domains by adding multiple entries to the `$whitelistPatterns` array, optionally using `getHostnamePattern()` for domains, like this:

```php
$whitelistPatterns = array(
  getHostnamePattern("example.net"),
  getHostnamePattern("facebook.com")
);
```
The only way you'd be able to limit proxy access to a specific Facebook page is to whitelist the page itself plus all hosts/URL patterns that are used for providing static assets for Facebook, which is probably not feasible since there are many of them and they probably change frequently.

**Comment by Jamman** [comment]
Thanks Josh - sorry to be such a noob and a pain!

Just I wondered if getting the regular expression working might help, if I could use several regular expressions... but I must have something wrong...

This doesn't work
`$whitelistPatterns = array([ @^https?://([a-z0-9-]+\.)*example\.net@i ]`

And if it did could I use...
'$whitelistPatterns = array(
[ @^https?://([a-z0-9-]+\.)*example\.net@i ],
[ @^https?://([a-z0-9-]+\.)*subdomain\.nextsite\.net@i ]
);`

**Comment by joshdick** [comment]
You need to quote your regular expressions. Untested, but try this instead:
```php
$whitelistPatterns = array([ "@^https?://([a-z0-9-]+\.)*example\.net@i" ]
```

**Comment by Jamman** [comment]
ok got it working - and well!
Need to remove the [ ] as below example

`$whitelistPatterns = array( "@^https?://([a-z0-9-]+\.)*example\.net@i" `

**Comment by Jamman** [comment]
`$whitelistPatterns = array(`
`"@^https?://([a-z0-9-]+\.)*example\.net@i",`
`"@^https?://([a-z0-9-]+\.)*subdomain\.nextsite\.net@i"`
`);`

**Comment by joshdick** [comment]
Oops, didn't catch that when I copy-pasted your example.

Glad you got it working! :-)

**Comment by Jamman** [comment]
Hello Josh,
A couple more issues/questions.
1) Is it possible to create a 'blacklist' as well as whitelist?
2) When I try to log in to some pages - social media - it does not let me log in... is this resolvable or a shortcoming of this kind of solution?

**Comment by joshdick** [comment]
I have covered the answers to these questions in #37.
