### ISSUE TITLE
Unable to fetch URL from Query parameter

### ISSUE THREAD

**Issue by r3ver53r** [joshdick/miniProxy#36]
Hi, 

As per the script, the domain should be entered in the below format:
https://mydomain.com/miniProxy.php/http://example.net/

Although, my web server is treating it as a normal path and giving a 404 error.

If I change the "/" to "?", as mentioned below, then the proxy works fine. Please check.
https://mydomain.com/miniProxy.php?http://example.net/

**Comment by r3ver53r** [comment]
Proposed fix on line 67:

define("PROXY_PREFIX", "http" . (isset($_SERVER['HTTPS']) ? "s" : "") . "://" . $_SERVER["SERVER_NAME"] . ($_SERVER["SERVER_PORT"] != 80 ? ":" . $_SERVER["SERVER_PORT"] : "") . $_SERVER["SCRIPT_NAME"] . "?");

**Comment by joshdick** [comment]
Out of curiosity, what web server are you using?

**Comment by r3ver53r** [comment]
It is nginx/1.10.0. 

You seem to be passing REST style params[0] which may not be supported by default.

[0] https://mydomain.com/miniProxy.php/REST_Param1

**Comment by htdat** [comment]
Just confirm this. 
I have the same issues with r3ver53r 
Server: nginx/1.4.6 (Ubuntu)

**Comment by prysme01** [comment]
Same here with nginx/1.9.10
Any workaround ?

**Comment by joshdick** [comment]
@r3ver53r Finally had time to test your proposed fix (wanted to make sure it played correctly with `POST` data.)

Everything looked good so I made the change; thanks for the suggestion!
