### ISSUE TITLE
Would it be simple enough to proxy a single webste without URL parameters?

### ISSUE THREAD

**Issue by andyg2** [joshdick/miniProxy#38]
I'm using this to bypass a firewall to gain access for a single website for an engineering firm
How could I go about rewriting the PROXY_PREFIX to remove the protocol and host of the target website so the script can operate as a clone of the target website. It would be running in the public_html directory.
As you know the code intimately what I'm looking for is a yes, it's simple just do this... or a no that's gonna be tricky kind of response.

Currently:
http://exampleproxy.com/miniProxy.php/http://target.com/page.html
Desired:
http://exampleproxy.com/directory/page.html

Or would mod_rewrite be easier? (just thought of that).

**Comment by joshdick** [comment]
Your idea to use `mod_rewrite` would likely be much easier than attempting to modify miniProxy do to this (since without mod_rewrite you would still see a `.php` extension somewhere in the URL), but I haven't tested miniProxy with `mod_rewrite`.
