### ISSUE TITLE
use miniproxy as library

### ISSUE THREAD

**Issue by alberto-bottarini** [joshdick/miniProxy#41]
Hi, comgrats for your mini-but-not-simple proxy.

I think that it will be a great idea the possibility to use miniproxy as a dependecies ant not only as a out-of-the-box proxy. Maybe you could introduce composer, oop and some documented apis to allow easy integration of your code into bigger applications.

For exemple i will use miniproxy in a laravel application, wrapping logic in a service class that will be injected using laravel DI.

If you like this idea, i could share with you some code.

**Comment by joshdick** [comment]
> mini-but-not-simple proxy

Couldn't be more true! 😆

This is an interesting idea. One of the chief goals of miniProxy is keeping it, well, mini. If attempting to refactor it so it can be used as a library with documented APIs makes it much larger, I'm not sure the idea is a great fit.

That said, I'm always willing to look at code; PRs are always welcome!

Thanks for the suggestion in any case!
