### ISSUE TITLE
Is there a way to show images hotlink protected

### ISSUE THREAD

**Issue by distante** [joshdick/miniProxy#47]
I find out there are a problem when you see some sites that have hotlink protection for images, those doesn't get show and when those are (for example) images for menu or similar the site doesn't sees too well. 

(Also when they don't have alt attribute is a nightmare!)

**Comment by aaronorosen** [comment]
Can you post a link of a website that has this issue running through the proxy?

**Comment by joshdick** [comment]
This issue could potentially be worked around by setting the referrer header to the originally-requested page (`CURLOPT_REFERER`) when requesting resources for that page, but that would require the proxy to be aware of the page it is requesting resources for at the time they're requested, which it currently is not.

**Comment by distante** [comment]
@aaronorosen Right now I do not have one in mind because I am on another project for a while but I have to get back to this soon. As soon as I find one I will added it to the first post.

@joshdick I see, I will dig into it when I get back to the project.

**Comment by BenNottelling** [comment]
Can you link a website that uses hotlink protection?

**Comment by joshdick** [comment]
Just pushed 7ddde300581fef6d3710d36918ade16dde124552 which may help with this issue by attempting to correctly rewrite the `Origin` header.
