### ISSUE TITLE
Feature request: URL form

### ISSUE THREAD

**Issue by dextronox** [joshdick/miniProxy#63]
Hi,

Are there any plans to implement a URL form/banner on proxied pages, to allow users to navigate to other pages, and possibly place advertisements on?

Kind regards,
Dextronox

**Comment by joshdick** [comment]
I know those are common features for web proxies, but there are currently no plans to add those features to miniProxy. Leaving out features not directly related to proxying is what helps keep miniProxy, well, mini. :)

Thanks for the suggestions though!
