### ISSUE TITLE
no proxy for links on proxify page

### ISSUE THREAD

**Issue by adam488** [joshdick/miniProxy#64]
Hi,

For example:
I have this page: http://www.mywebsite.com/miniProxy.php?http://www.proxifysite.com
If is some links on the above page and I click its, then I will redirected through miniProxy at the link clicked.
http://www.mywebsite.com/miniProxy.php?http://www.linkclicked.com
What I need to change on miniProxy.php code to go directly at the link clicked, not through miniProxy page. http://www.linkclicked.com

Thanks

**Comment by joshdick** [comment]
miniProxy works the way you're describing by design/on purpose, but to get it to do what you're asking, you can locally change the following line:

```php
$proxifyAttributes = array("href", "src");
```

To look like this instead:

```php
$proxifyAttributes = array("src");
```

 I hope that helps!

**Comment by adam488** [comment]
Hi again,

Not working. After this change, the page is not display correctly.
Please look: http://btc-info.site11.com/miniProxy.php?https://blockchain.info/popular-addresses
Any other suggestion?

Many thanks

**Comment by joshdick** [comment]
Oops my bad, thought of that (and the next solution below, actually! 😜) without testing.

Try this change instead, on a stock `miniProxy.php` (DON'T make the change discussed above):

Above this line:

```php
$attrContent = $element->getAttribute($attrName);
```

Add one new line above that line so it looks like this:

```php
if ($element->tagName === "a") continue;
$attrContent = $element->getAttribute($attrName);

```
