### ISSUE TITLE
can't handle youtube

### ISSUE THREAD

**Issue by sbw983** [joshdick/miniProxy#65]
Hello
I am in china and miniproxy help me a lot.
miniProxy work very good on my godaddy server . but there is an issue that miniproxy can open youtube but can't open the video. i f this can fix, it will be great.
thank u

**Comment by BenNottelling** [comment]
Just open the link for youtube, don't go to youtube and find the video that way, Google for the video you want and copy the link into miniproxy

**Comment by zxq2233** [comment]
我修复好了，你要不要

**Comment by sbw983** [comment]
@zxq2233 如果能提供最好啦，不过用得不多，自己买了个支持php的服务器主要做google的镜像，另外买了个vps架了个ShadowSocks服务。得多准备几把梯子，没办法

**Comment by yzweb2018** [comment]
楼上的来一份啊
