### ISSUE TITLE
There is no HOWTO

### ISSUE THREAD

**Issue by ZwickTheGreat** [joshdick/miniProxy#66]
There is no single word about how to use this proxy.

**Comment by joshdick** [comment]
There is in fact one sentence about it in the README. :)

> ## Installation and Use
>
> Simply copy `miniProxy.php` to your web server (it's okay to rename it) and access it directly. That's it! You'll be presented with further usage instructions.

What other documentation do you think is needed?

**Comment by ZwickTheGreat** [comment]
Hah. Weird. It shows nothing for me, so I thought, that there is no usage instructions. :-)

Now I see that there should be this:
https://github.com/joshdick/miniProxy/blob/master/miniProxy.php#L243

There must be something wrong with my PHP server / whatever.

**Comment by joshdick** [comment]
Well if you've confirmed that other PHP scripts work fine, can you tell me your PHP version?

Is there anything noteworthy in your server logs?

**Comment by ZwickTheGreat** [comment]
PHP Version 5.3.3

That's it. :)

Sorry about that. Maybe it would be fine to have some error message if PHP Version 5.3.3.

**Comment by joshdick** [comment]
This line is supposed to do just that: https://github.com/joshdick/miniProxy/blob/master/miniProxy.php#L28

Not sure why it didn't work in your setup.
