### ISSUE TITLE
Cookie for Single User Proxy

### ISSUE THREAD

**Issue by PeteLambert** [joshdick/miniProxy#68]
Hi there,

I'm hoping to use this to run a small personal service app through. The no-cookie thing is preventing my from logging into my site.

Is the a fix / crack / patch etc for a single-user situation like mine? I don't work in php, but I work in python so I maybe be able to fuddle if you have ideas.

Thank you kindly,

**Comment by joshdick** [comment]
Minimally, you'd need to add a few more cURL options in the section of the miniProxy code with the `//Other cURL options.` comment:

```php
curl_setopt($ch, CURLOPT_COOKIEJAR, "cookies.txt");
curl_setopt($ch, CURLOPT_COOKIEFILE, "cookies.txt);
```

This mechanism is also the basis of #24.

I haven't tested this so I'm not sure if those are the only changes necessary to get cookies working the way you're describing.

**Comment by joshdick** [comment]
I just opened #69 for cookie support. It works in very basic testing but isn't production ready; use it at your own risk!
