### ISSUE TITLE
How do you extract the URL?

### ISSUE THREAD

**Issue by BenNottelling** [joshdick/miniProxy#71]
Something that is throwing me off is how you get URL without a parameter and no value, looking into $_GET you would need a parameter then a value, so how do you extract it when the URL itself will be the parameter?

**Comment by joshdick** [comment]
If you make a test PHP program `test.php` that looks like this:

```php
<?php print_r($_GET); ?>
```

And load the proxy in a browser like this:

`miniProxy.php?path/to/test.php?key=value&keywithnovalue`

You see this as output, which is exactly the same as when `test.php` isn't loaded through the proxy at all:

`Array ( [key] => value [keywithnovalue] => )`

So to confirm, the proxy correctly handles GET parameters both with and without values.

I assume you're asking your question since the query string question mark appears in URLs twice for this case?

The answer lies on this line of miniProxy.php:

```
$url = substr($_SERVER["REQUEST_URI"], strlen($_SERVER["SCRIPT_NAME"]) + 1);
```

This line strips the proxy URL and question mark out of the URL that is sent to cURL, so that 
`miniProxy.php?path/to/test.php?key=value&keywithnovalue` becomes `test.php?key=value&keywithnovalue` with a proper/single query string, which is what is sent to cuRL to make the proxied request.

I hope that answers your question, so I'm closing this issue, but feel free to continue the dialog either way!

**Comment by BenNottelling** [comment]
@joshdick That does explain it quite well, I also have a question about whitelisting sites, is this the correct way to do it?
```
$whitelistPatterns = array(
  //Usage example: To support any URL at example.net, including sub-domains, uncomment the
  //line below (which is equivalent to [ @^https?://([a-z0-9-]+\.)*example\.net@i ]):
  getHostnamePattern("youtube.com")
  getHostnamePattern("googlevideo.com")
  getHostnamePattern("ytimg.com")
  getHostnamePattern("googleusercontent.com")
  getHostnamePattern("apis.google.com")
  getHostnamePattern("gstatic.com")
);
```

**Comment by BenNottelling** [comment]
Also, I'm testing the idea about a plugin for each domain to allow for a bit more functionality and I just wanted to know what you thought about the idea and my quickly written code that I haven't tested yet :)
https://github.com/BenNottelling/miniProxy/tree/Plugin-Work

**Comment by joshdick** [comment]
Regarding `$whitelistPatterns`, that is indeed the correct way to do it, your array elements just need commas between them. :)

Your plugin mechanism is an interesting idea, but I probably wouldn't integrate it into miniProxy yet. The plugin idea is simple enough that a sufficiently advanced user could figure out how to implement a mechanism on their own just like you did, but I feel that miniProxy itself, at least in its current state, itself doesn't expose enough integration points to allow for a sufficient variety of useful plugins to exist.

**Comment by BenNottelling** [comment]
@joshdick okay thank you and I'm designing it so that it will still function with only the miniProxy.php file and it will only effect the proxy if the plugin file exists, I was also thinking it could have a use to ensure that only the necessary domain are connected to which could result in less bandwidth usage although from what I can tell I would have to update how the whitelist system works

**Comment by joshdick** [comment]
:+1:

**Comment by BenNottelling** [comment]
If I'm not mistaken this path won't work correctly, how can I fix it? I can't add a backslash because it causes a phase error.
`'plugins'.'/'.$domain.'.php'`
How can I correctly point it to the file for this code?
`include 'plugins'.'/'.$domain.'.php';//If it exists load the plug-in file for the selected website. `

**Comment by joshdick** [comment]
Try this instead (untested, should also work on Windows):

```php
include realpath("plugins/$domain.php");
```

**Comment by BenNottelling** [comment]
Okay than you

**Comment by BenNottelling** [comment]
@joshdick This is really confusing me, I am trying to allow the host to set the proxy to only request mobile pages, but it for some reason fails and claims that the variable useMobilePage is undefined, even though I define it at the config file with `$useMobliePage = true;` Whats going wrong here?
```
  if (!$useMobliePage) {
	if (empty($user_agent)) {
		$user_agent = "Mozilla/5.0 (compatible; miniProxy)";
	}
  }else{
  	$user_agent = "Mozilla/5.0 (iPhone;)";
  }
```

**Comment by joshdick** [comment]
What's wrong is that you have a typo. You are using `$useMobliePage` in your `if` statement when you probably meant to use `$useMobilePage`.

**Comment by BenNottelling** [comment]
@joshdick just a thought, but perhaps the input should have autocomplete disabled for a little bit more security? Right now if a user enters a URL it will show up again when they visit the page which is not ideal for privacy

**Comment by joshdick** [comment]
@BenNottelling It won't hurt anything, so done as of eee9512, but that wouldn't prevent proxied pages from showing up in the user's browser history.

**Comment by BenNottelling** [comment]
@joshdick no it won't lol, but it's still a nice addition
