### ISSUE TITLE
miniProxy not re-directing with Roku device

### ISSUE THREAD

**Issue by matrixebiz** [joshdick/miniProxy#75]
Hello, I am trying to stream an m3u8 video link through your proxy VIA another m3u8 file like;
My link - http://myserver.com/playlist.m3u8

Contents of that playlist.m3u8;
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=10000,RESOLUTION=640x360,
#EXTINF:-1,
http://myserver.com/miniProxy.php?http://ExternalServer.com/mainvideo.m3u8

now, this works fine with VLC Player in windows but the Roku does not seem to want to re-direct through the proxy :( is there any change I can do with the script to fix this? not sure if I enable CORS or it is having an issue with the device HTTP_USER_AGENT or what. Hoping you can help me with this.

Thank you

**Comment by joshdick** [comment]
It would be useful to know the differences between both the response body and headers of the m3u8 file when served proxied vs. unproxied.

**Comment by matrixebiz** [comment]
Hi Josh, not sure what that means but I've found another solution. Thanks anyway

**Comment by abdelaliajbary** [comment]
@matrixebiz Hello, can you share with us your solution ? i will appreciate it

**Comment by matrixebiz** [comment]
Hello, unfortunately it doesn't work on Roku so I have abandoned it.

**Comment by abdelaliajbary** [comment]
can you PM me your skype ?
