### ISSUE TITLE
What PHP version is required...

### ISSUE THREAD

**Issue by recolic** [joshdick/miniProxy#76]
I'm using PHP 5.3.29 with apache, and got this error:
 PHP Parse error:  syntax error, unexpected '[' in /var/www/html/miniProxy.php on line 187

If I should have my php updated, can you note its php requirement in README.md? That's more convenience. Thanks a lot.

**Comment by joshdick** [comment]
PHP 5.4.7 or later is required. There is already a note about that in the README.
