### ISSUE TITLE
Proxy fails when accessing website on CloudFlare

### ISSUE THREAD

**Issue by hansng7** [joshdick/miniProxy#78]
I get error message "DNS points to prohibited IP" when trying to access to websites on CloudFlare.

Source:
- https://support.cloudflare.com/hc/en-us/articles/200171826-Error-1002-DNS-points-to-Prohibited-IP
- https://github.com/technoboy10/crossorigin.me/issues/89

**Comment by BenNottelling** [comment]
Solution found in one of my branches. Add this in the additional cURL options, 
//Atempt to report the users real IP (fixes security message on Facebook)
	curl_setopt($ch, CURLOPT_HTTPHEADER, array("X-Forwarded-For: $ip"));
Or use my branch and create a config file for the domain that's broken based off the Facebook config
https://github.com/BenNottelling/miniProxy/tree/ConfigCookies

**Comment by BenNottelling** [comment]
Solution found in one of my branches. Add this in the additional cURL options, 
//Atempt to report the users real IP (fixes security message on Facebook)
	curl_setopt($ch, CURLOPT_HTTPHEADER, array("X-Forwarded-For: $ip"));
Or use my branch and create a config file for the domain that's based off the Facebook config
https://github.com/BenNottelling/miniProxy/tree/ConfigCookies

**Comment by joshdick** [comment]
I have added an `$anonymize` setting to miniProxy in 0a059c0 to control sending an `x-forwarded-for` header.

I tried loading a CloudFlare-hosted site (medium.com) and it loaded just fine even with `$anonymize = true;`, so I'm not sure whether it really solves the issue?

**Comment by BenNottelling** [comment]
I only noticed it when both the host and the website I'm trying to connect to were both on cloudflare

**Comment by BenNottelling** [comment]
Can been seen here: http://www.bennottelling.ml/index.php?medium.com (I was writing code to check for cloudflare and then correct for it, just to explain that error)

**Comment by joshdick** [comment]
I had only tried loading the front page earlier, I see that Medium articles accessed at custom domains do indeed have problems.

I suspect this is actually a problem with the `Origin` header sent by miniProxy.

**Comment by joshdick** [comment]
Just pushed 7ddde300581fef6d3710d36918ade16dde124552 which may help with this issue.

**Comment by BenNottelling** [comment]
@joshdick Issue is still happening with 7ddde30

**Comment by daiaji** [comment]
@joshdick The problem seems to be in the http://tw.gigacircle.com/3671117-1

**Comment by ash121121** [comment]
i fixed this in a different proxy script by removing cloudflares headers and setting a X-Fowarded-for header

**Comment by RubyTheRose** [comment]
Any information regarding this problem? I don't see a solution other then disabling anonymize.

**Comment by BenNottelling** [comment]
@RubyTheRose yeah, it doesn't help. Try doing what @ash121121 suggested

**Comment by ash121121** [comment]
ive not looked into fixing this for miniproxy but for PHP-PROXY i created a plugin and used the code below. im setting the xforwarded-for header and clearing cloudflares headers.

`<?php

use Proxy\Plugin\AbstractPlugin;
use Proxy\Event\ProxyEvent;

class CloudflarePlugin extends AbstractPlugin {

    protected $cloudflareHeaders = array();

    public function onBeforeRequest(ProxyEvent $event){
        $event['request']->headers->set('X-Forwarded-For', $_SERVER["HTTP_CF_CONNECTING_IP"]);
        // clear Cloudflare headers
        $event['request']->headers->remove('Cf-Ray');
        $event['request']->headers->remove('Cf-Ipcountry');
        $event['request']->headers->remove('Cf-Visitor');
        $event['request']->headers->remove('Cf-Connecting-Ip');
    }
}`
