### ISSUE TITLE
http error 500

### ISSUE THREAD

**Issue by nkp002** [joshdick/miniProxy#80]
**I am getting HTTP error 500 when I provide url to it or click proxy it button.
For eg. http://shiningsword.dlinkddns.com/miniProxy.php?http://www.akubihar.com
I am using apache2 with** 
PHP 7.1.6-2 (cli) (built: Jun 14 2017 05:31:31) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.6-2, Copyright (c) 1999-2017, by Zend Technologies

**php -m**
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
enchant
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
interbase
intl
json
ldap
libxml
mbstring
mcrypt
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
PDO_Firebird
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
pspell
readline
recode
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib
[Zend Modules]
Zend OPcache

**php -i | grep curl**
/etc/php/7.1/cli/conf.d/20-curl.ini,
curl

**cat /etc/php/7.1/cli/conf.d/20-curl.ini**
; configuration for php curl module
; priority=20
extension=curl.so

**/etc/apache2/conf-enabled# ls**
charset.conf            localized-error-pages.conf    security.conf
javascript-common.conf  other-vhosts-access-log.conf  serve-cgi-bin.conf

**/etc/apache2/mods-enabled# ls**
access_compat.load  authz_host.load  dir.load     mpm_prefork.conf  setenvif.load
alias.conf          authz_user.load  dnssd.conf   mpm_prefork.load  status.conf
alias.load          autoindex.conf   dnssd.load   negotiation.conf  status.load
auth_basic.load     autoindex.load   env.load     negotiation.load
authn_core.load     deflate.conf     filter.load  php7.0.conf
authn_file.load     deflate.load     mime.conf    php7.0.load
authz_core.load     dir.conf         mime.load    setenvif.conf

**I am unable to find problem?**

**Comment by joshdick** [comment]
Do you have any relevant error logs (usually the web server error logs?)

**Comment by nkp002** [comment]
[:error] [pid 2541] [client 117.197.74.111:53864] PHP Fatal error:  Uncaught Error: Call to undefined function mb_detect_encoding() in /var/www/html/miniProxy.php:340\nStack trace:\n#0 {main}\n  thrown in /var/www/html/miniProxy.php on line 340, referer: https://shiningsword.dlinkddns.com/miniProxy.php

**Comment by joshdick** [comment]
That error would normally happen if PHP's `mbstring` module isn't installed, but based on your `php -m` output above, it looks like your server does indeed have that module installed. Is it possible that your PHP configuration is good, but that you just need to restart Apache for it to be picked up?

**Comment by nkp002** [comment]
I have restarted but still there is error.
I don't know why?

**Comment by nkp002** [comment]
I have reinstall phpmbstring
and it still show HTTP 500 error and error log is
PHP Fatal error:  Uncaught Error: Class 'DomDocument' not found in /var/www/html/miniProxy.php:346\nStack trace:\n#0 {main}\n  thrown in /var/www/html/miniProxy.php on line 346

**Comment by joshdick** [comment]
Looks like now there's a problem with your `xml` module. Did all of your PHP modules somehow get corrupted?

**Comment by nkp002** [comment]
may be. I had tried a lot by installing php7.0 and php7.1.

**Comment by nkp002** [comment]
now I have installed apt-get install php7.0-xml
And now it is working...
Thanks a lot...

**Comment by joshdick** [comment]
You're quite welcome! 🙂

**Comment by daiaji** [comment]
@joshdick Does this question need to be added to the readme?

**Comment by joshdick** [comment]
@daiaji Good idea. Done, per 3c22f03.
