### ISSUE TITLE
Try to load website with no post

### ISSUE THREAD

**Issue by ocuil** [joshdick/miniProxy#82]
Hi,
I want to embebed the script to call from inside a web with no _POST var,
I add:
`$url = ("http://localhost:8880/0.html");`
before:
`if (empty($url)) {`

because I try to:
`echo $url;`
in the same place, to know how is the var.

Bat that only load partial website ... maybe that array have more info? I try to know...

Thanks a lot

**Comment by BenNottelling** [comment]
What if you just replace `$url = substr($_SERVER["REQUEST_URI"], strlen($_SERVER["SCRIPT_NAME"]) + 1);` with `$url = ("http://localhost:8880/0.html");`rather than what you did above? It could also be that miniProxy can't proxify your webpage correctly..

**Comment by ocuil** [comment]
Thanks a lot Ben but do not works ... I get the same error:

```
miniProxy.php?http://localhost:19999/dashboard.js?v20170724-7:2 Uncaught SyntaxError: Unexpected token <

miniProxy.php:96 Uncaught ReferenceError: NETDATA is not defined
    at miniProxy.php:96
(anonymous) @ miniProxy.php:96
```

**Comment by BenNottelling** [comment]
😭😭😭 I guess it's up to joshdick now, I'll dig around in the morning if I remember. For now I'm off to sleep! It's 1:30am XD

**Comment by ocuil** [comment]
Oh!!! sorry men, go to sleep and thanks very much about your help !!! nn

**Comment by BenNottelling** [comment]
Okay so, `$url = ("http://localhost:8880/0.html");` isn't even correct code, use `$url = "http://localhost:8880/0.html";` instead, I used this with google and it worked fine BUT you will be unable to   follow links and if the page redirects it will cause an infinite loop. There also may be a problem with using local host, but I'm not sure

**Comment by ocuil** [comment]
Hi !!! I hope you sleep well :-)
Thanks for your help, but that donts works ... :-(
When I add an `echo $url;` to see what is the value of, the whole script fails ... with only one echo as debug ... I'm really confuse about that ...

**Comment by BenNottelling** [comment]
What if you use this https://github.com/BenNottelling/miniProxy/tree/patch-1 and only edit the $defaulturl option? I used that script and it worked perfectly, also perhaps your server is causing an issue? Could you screenshot the error or upload the log or something like that?

**Comment by ocuil** [comment]
Wow!!! works very wel !!! thanks a lot !!! thanks very much :-)

**Comment by BenNottelling** [comment]
You can embed it with an iframe, also please close this issue as it's 🐝 solved
