### ISSUE TITLE
duckduckgo.com returns a blanck page

### ISSUE THREAD

**Issue by fredbcode** [joshdick/miniProxy#87]
With duckduckgo.com a search returns a blank page without an error
More or less the same problem with qwant.com

**Comment by cybnz** [comment]
For me this is for all sites.

**Comment by fredbcode** [comment]
I don't agree, works very well but there are some specifics cases

**Comment by cybnz** [comment]
Actually it seems to me that anything with HTTPS doesn't work.  This may be due to the fact that I have HTTPS on my site...
