### ISSUE TITLE
Add content to the body?

### ISSUE THREAD

**Issue by BenNottelling** [joshdick/miniProxy#88]
How can content (like an image) be added to an HTML `<body> </body>`?

**Comment by joshdick** [comment]
Can you give more context here?

**Comment by joshdick** [comment]
@BenNottelling bump

**Comment by BenNottelling** [comment]
I was thinking about adding the coinhive script, but I don't really want to have the site marked as "malware/viruses" so I'll pass on it

**Comment by colroyce** [comment]
Hi! Thank you for this great proxy!
How can I add any additional content to proxified page? E.g. banner or text (and google analytics code maybe), preferably to header?

**Comment by joshdick** [comment]
@colroyce The answer is probably too complicated to explain in a GitHub issue, but the most straightforward way would be to use the [DOMDocument] (http://php.net/manual/en/class.domdocument.php) APIs to append content to `$doc` right before the `$doc->saveHTML();` call at the bottom of the script.

**Comment by colroyce** [comment]
Oh, thank you so much!

**Comment by joshdick** [comment]
@colroyce You're welcome!
