### ISSUE TITLE
How to use this library ?

### ISSUE THREAD

**Issue by NgKhanh** [joshdick/miniProxy#93]
I tried some code but it not show anything
```
include_once('/libraries/miniProxy.php');
return makeRequest('https://google.com');
```

Anyone help with some code?

**Comment by BenNottelling** [comment]
miniProy isn't a library. Just access the "miniProxy.php" file from within your web browser and enter the URL you want.
![miniproxy](https://user-images.githubusercontent.com/17304943/32116725-abac86d6-bb00-11e7-9ebb-509555201166.PNG)
Or at the end of the script add ?domainyouwant.com. Like this:
![miniproxy2](https://user-images.githubusercontent.com/17304943/32116836-0a711dd0-bb01-11e7-8a48-f508fb0060dd.PNG)
Please read the readme next time.
https://github.com/joshdick/miniProxy/blob/master/README.md
