### ISSUE TITLE
html <base> tag not managed

### ISSUE THREAD

**Issue by PiR43** [joshdick/miniProxy#94]
The html tag "`<base>`" allow to change  the base URL to use for all relative URLs (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)

Exemple of url who use it and don't work with miniProxy:
http://play.grafana.org/dashboard/db/grafana-play-home?orgId=1

**Comment by BenNottelling** [comment]
This gave me an idea..
adding `document.write(\"<base href=\"http://\" + document.location.host + \"" />\");`
just under  
 ```
$scriptElem = $doc->createElement("script",
      '(function() {
```
actually fixes logging in on Netflix, which is cool! (I haven't done other testing, but still.)
