### ISSUE TITLE
After login the proxy is redirect to real website

### ISSUE THREAD

**Issue by miyakedev** [joshdick/miniProxy#95]
When I access my account in a web page, I am redirected to the real page.

**Comment by joshdick** [comment]
miniProxy doesn't (yet) support cookies, but you may have better luck with the [experimental cookie support branch](https://github.com/joshdick/miniProxy/pull/69).

**Comment by BenNottelling** [comment]
I think they means that it redirects to the original page.. like google.com rather than running it through the proxy like miniProxy.php?google.com
