### ISSUE TITLE
XMLHttpRequest POST requests are not handled properly

### ISSUE THREAD

**Issue by henrywood** [joshdick/miniProxy#96]
Hi !

I am trying to get miniProxy working. However, for XMLHttpRequest POST requests the origin server insists on throwing HTTP status code 400 at me.

I have two versions of my page:
https://signer.cnlovematch.com/reportdemo/index4.php 
where the included IFRAME does NOT USE MINIPROXY and the contents/application in the IFRAME works correctly.

Another version:
https://signer.cnlovematch.com/reportdemo/index5.php
sends the IFRAME's src through miniProxy and the contents/application in the IFRAME does not work.
Apparently, this is due to the fact that XMLHttpRequest POST requests from within the IFRAME throws HTTP status 400 (Bad request)

NOTE: To get miniProxy to better handle XMLHttpRequest  GET requests, I have changed miniProxy slightly. The source of the file used can be viewed here:

https://signer.cnlovematch.com/reportdemo/source.php?file=proxy.php

I think that part of the problem is that the original server seems to send either text/plain, application/json or text/xml as Content-Type in responses that are actually all JSON responses.

Does anybody have any ideas ?

**Comment by joshdick** [comment]
It looks like this is happening because miniProxy is somehow not properly handling the CSRF_TOKEN cookie set by the application (even when using the branch with #69), so it seems like the errors are probably happening because the 

```xml
```
