### ISSUE TITLE
Need Help ?

### ISSUE THREAD

**Issue by agadirian** [joshdick/miniProxy#99]
I just copy the miniproxy file to my own server but when I proxied this source "http://145.239.218.240/p.php?http://iptvfree1.com:6969/live/live:e17869582e1a2368/iy7lSeX4Z7/1089.m3u8" I got 

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:2127
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:2
#EXTINF:0.950944,
/hlsr/TREJUUoMFw0WBAAADQUABgBRUFBTAwpWA1AHDlRVWVRXVlUJCQdTVgVEHRtHQxFSA19sXwEVCQEBXl0UQxYSVURsCFQbXhcGAV8HCRYbQUMLX1YUXwcfEkEPABpbQVAHDwRWEhVGUE9AA0NXVVs8UwdEWlUAFQleRAoIFEMMD29SVgxRVwAXDRZWExUWXhBHQAgReTN/E2NwNUYUQwEIRERSFVUbXhcDAVMAGxgVAFgXXEdEHBUJEnc0RhRDBhlEU10SWVYKFw0WCwJMDBVPFQtBbEQAREdCVAcJXRNBWxIHEU0SVAVNaFcJX1dRVBdeDVxAFF8VAgETSkZVDg0IRFlBPkBQABcNFlcEDAQEQUo=/live:e17869582e1a2368/iy7lSeX4Z7/1089/ea6f4d86df7c9e47e6f173c0c598d46a/1089_2127.ts

and when I proxied it with another miniproxy that I found on google "http://genti.goats.stream/p.php?http://iptvfree1.com:6969/live/live:e17869582e1a2368/iy7lSeX4Z7/1089.m3u8" it
give me an other result , May I know the difference between mine and last one.

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:2097
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:2
#EXTINF:1.084411,
http://185.59.220.183:25461/live/live:e17869582e1a2368/iy7lSeX4Z7//hlsr/TREJUUoMFw0WBFdfDAFTAwcBAFNVBFcJBlMHCFFbBAcFUVRTW1JTBgdEHRtHQxFSA19sXwEVCQEBXl0UQxYSVURsCFQbXhcGAV8HCRYbQUMLX1YUXwcfEkEPABpbQVAHDwRWEhVGUE9AA0NXVVs8UwdEWlUAFQleRAoIFEMMD29SVgxRVwAXDRZWExUWXhBHQAgRYBBbR0IRLgtUBQoPV0UTLXx6RhkVVg9FS1VDBhVYEAcDUAYRHBMFC00PFxNJFAlDdmtGGRVRHkVcWkQKWAwQCRQIBEYIE0pGURI8E1VFRxNVWAlQRRZcEwgWG0FaA0psVQpZXVVSEg1XDxBDChQCUBIVRlhYWg9FVkZoE14GEAkUVAIGAAJEGQ==/live:e17869582e1a2368/iy7lSeX4Z7/1089/79d65849c9c435d7a3a558f46bd0a42e/1089_2097.ts

**Comment by joshdick** [comment]
That m3u link is no longer working for me, but I tried testing with a few of the sample URLs listed at http://g33ktricks.blogspot.com/2016/04/list-of-hls-streaming-video-sample-test.html and cannot reproduce the issue, nothing gets corrupted.

Are you still able to reproduce this issue? Which web server and version of PHP are you using to run miniProxy?
